name: Build and push to nuget feed

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    - name: Setup .NET
      uses: actions/setup-dotnet@871f041373faaad213a635d9afb62905ec029bbb # v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Pack
      run: dotnet pack -c Release
    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push SpeedTest/bin/Release/*.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/safervpn/index.json --skip-duplicate 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}